name: Testing Workflow

on:
  push:
    branches: 
      - master

jobs:
  testing:
    name: Lint Check and Testing
  
    runs-on: [ubuntu-latest]
    
    steps: 
      - name: Clone Repo
        uses: actions/checkout@v1
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      # Check the code with Android linter
      - name: Run Android Linter
        run: ./gradlew lintMasterDebug

      # Step 4: Yun your unit tests
      - name: Run Unit Tests
        run: ./gradlew testMasterDebugUnitTest
    
           
